M48
; DRILL file {KiCad 9.0.4} date 2026-05-02T13:51:30+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-02T13:51:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X52.0Y-45.0
X115.0Y-144.0
X186.0Y-124.0
X225.0Y-46.0
M30
