M48
; DRILL file {KiCad 9.0.4} date 2026-05-02T13:54:13+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-02T13:54:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.0472Y-1.7717
X4.5276Y-5.6693
X7.3228Y-4.8819
X8.8583Y-1.811
M30
